### ISSUE TITLE
Issue when UITabBarItem's title is positioned next to image

### ISSUE THREAD

**Issue by rdoubleui** [odedharth/SuperBadges#1]
In general I was wondering if you still maintain this repository? I tried your approach and found that it only works for tab bar items that got their caption underneath as you're relying on the middle of the tab bar item to position the indicator/badge.

I'd suggest an approach where the indicator/badge would be positioned based on the actual position of the image within the tab bar item. Would be interested in accepting pull requests to fix this issue?

**Comment by odedharth** [comment]
@rdoubleui feel free to send a pull request 👍

**Comment by rdoubleui** [comment]
#2
